//! Parser for context-generator output format.
//!
//! This module provides the core parsing functionality to read the specific format
//! generated by context-generator and convert it back into file structures.
//!
//! # Format Specification
//!
//! The context-generator output format consists of:
//! - File sections separated by exactly 20 dashes: `--------------------`
//! - File path specification: `file: <relative_path>`
//! - Content lines indented with exactly 4 spaces
//! - Final separator at the end

use thiserror::Error;

/// Parser state machine for tracking progress through the context format
#[derive(Debug, PartialEq, Clone)]
pub enum ParserState {
    /// Expecting a separator line (20 dashes)
    ExpectingSeparator,
    /// Expecting a file path line starting with "file: "
    ExpectingFilePath,
    /// Expecting the content separator (20 dashes after file path)
    ExpectingContentSeparator,
    /// Reading file content (lines with 4-space indentation)
    ReadingContent,
}

/// Core parser structure that maintains state during parsing
#[derive(Debug)]
pub struct Parser {
    /// Current parser state
    state: ParserState,
    /// File currently being parsed (if any)
    current_file: Option<ParsedFile>,
    /// Collection of successfully parsed files
    files: Vec<ParsedFile>,
    /// Current line number for error reporting
    line_number: usize,
}

/// Represents a successfully parsed file from the context format
#[derive(Debug, Clone)]
pub struct ParsedFile {
    /// Relative path of the file
    pub path: String,
    /// File content as individual lines (without indentation)
    pub content: Vec<String>,
    /// Line range where this file appeared in the input (start, end)
    pub line_range: (usize, usize),
}

/// Result of parsing operation containing files and any issues encountered
#[derive(Debug)]
pub struct ParseResult {
    /// Successfully parsed files
    pub files: Vec<ParsedFile>,
    /// Non-fatal warnings encountered during parsing
    pub warnings: Vec<String>,
    /// Fatal errors that prevented parsing
    pub errors: Vec<String>,
}

/// Comprehensive error types for import operations
#[derive(Debug, Error)]
pub enum ImportError {
    /// Format validation errors with specific line context
    #[error("invalid format at line {line}: {message}")]
    Format { line: usize, message: String },

    /// File path validation failures
    #[error("file path validation failed: {path} - {reason}")]
    PathValidation { path: String, reason: String },

    /// I/O operation failures during file creation
    #[error("I/O error for file {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
}

impl Parser {
    /// Create a new parser instance ready to process input
    pub fn new() -> Self {
        Self {
            state: ParserState::ExpectingSeparator,
            current_file: None,
            files: Vec::new(),
            line_number: 0,
        }
    }

    /// Parse the complete input string and return the result
    pub fn parse(input: &str) -> Result<ParseResult, ImportError> {
        let mut parser = Self::new();

        for line in input.lines() {
            parser.line_number += 1;
            parser.process_line(line)?;
        }

        // Handle end of input - ensure we're in a valid final state
        parser.finalize()
    }

    /// Process a single line according to current parser state
    fn process_line(&mut self, line: &str) -> Result<(), ImportError> {
        match self.state {
            ParserState::ExpectingSeparator => {
                self.handle_separator_line(line)?;
            }
            ParserState::ExpectingFilePath => {
                self.handle_file_path_line(line)?;
            }
            ParserState::ExpectingContentSeparator => {
                self.handle_content_separator_line(line)?;
            }
            ParserState::ReadingContent => {
                self.handle_content_line(line)?;
            }
        }
        Ok(())
    }

    /// Handle separator line validation (exactly 20 dashes)
    fn handle_separator_line(&mut self, line: &str) -> Result<(), ImportError> {
        if line != "--------------------" {
            return Err(ImportError::Format {
                line: self.line_number,
                message: format!("expected separator with exactly 20 dashes, found: {line}"),
            });
        }

        self.state = ParserState::ExpectingFilePath;
        Ok(())
    }

    /// Handle file path line (must start with "file: ")
    fn handle_file_path_line(&mut self, line: &str) -> Result<(), ImportError> {
        if !line.starts_with("file: ") {
            return Err(ImportError::Format {
                line: self.line_number,
                message: format!("expected 'file: <path>', found: {line}"),
            });
        }

        let path = line[6..].to_string(); // Remove "file: " prefix

        // Basic path validation
        if path.is_empty() {
            return Err(ImportError::PathValidation {
                path: path.clone(),
                reason: "file path cannot be empty".to_string(),
            });
        }

        self.current_file = Some(ParsedFile {
            path,
            content: Vec::new(),
            line_range: (self.line_number, self.line_number), // Will update end later
        });

        self.state = ParserState::ExpectingContentSeparator;
        Ok(())
    }

    /// Handle content separator line (another 20 dashes)
    fn handle_content_separator_line(&mut self, line: &str) -> Result<(), ImportError> {
        if line != "--------------------" {
            return Err(ImportError::Format {
                line: self.line_number,
                message: format!(
                    "expected content separator with exactly 20 dashes, found: {line}"
                ),
            });
        }

        self.state = ParserState::ReadingContent;
        Ok(())
    }

    /// Handle content line (must be indented with exactly 4 spaces or be another separator)
    fn handle_content_line(&mut self, line: &str) -> Result<(), ImportError> {
        // Check if this is the end separator (transition to next file or end)
        if line == "--------------------" {
            self.complete_current_file()?;
            self.state = ParserState::ExpectingFilePath;
            return Ok(());
        }

        // Content line must start with exactly 4 spaces
        if !line.starts_with("    ") {
            return Err(ImportError::Format {
                line: self.line_number,
                message: format!(
                    "content line must be indented with exactly 4 spaces, found: {line}"
                ),
            });
        }

        // Remove the 4-space indentation and add to current file content
        let content_line = line[4..].to_string();
        if let Some(ref mut file) = self.current_file {
            file.content.push(content_line);
            file.line_range.1 = self.line_number; // Update end line
        }

        Ok(())
    }

    /// Complete the current file and add it to the files collection
    fn complete_current_file(&mut self) -> Result<(), ImportError> {
        if let Some(file) = self.current_file.take() {
            self.files.push(file);
        }
        Ok(())
    }

    /// Finalize parsing and create the result
    fn finalize(mut self) -> Result<ParseResult, ImportError> {
        // If we have a current file in progress, complete it
        if self.current_file.is_some() {
            // We should be in ReadingContent state and expecting a final separator
            // For now, we'll allow ending without the final separator for flexibility
            self.complete_current_file()?;
        }

        Ok(ParseResult {
            files: self.files,
            warnings: Vec::new(),
            errors: Vec::new(),
        })
    }
}

impl Default for Parser {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parser_state_enum() {
        // Test that we can create and compare parser states
        assert_eq!(
            ParserState::ExpectingSeparator,
            ParserState::ExpectingSeparator
        );
        assert_ne!(
            ParserState::ExpectingSeparator,
            ParserState::ExpectingFilePath
        );
    }

    #[test]
    fn test_parser_creation() {
        let parser = Parser::new();
        assert_eq!(parser.state, ParserState::ExpectingSeparator);
        assert_eq!(parser.line_number, 0);
        assert!(parser.files.is_empty());
        assert!(parser.current_file.is_none());
    }

    #[test]
    fn test_parsed_file_structure() {
        let file = ParsedFile {
            path: "test.rs".to_string(),
            content: vec!["fn main() {".to_string(), "}".to_string()],
            line_range: (1, 5),
        };

        assert_eq!(file.path, "test.rs");
        assert_eq!(file.content.len(), 2);
        assert_eq!(file.line_range, (1, 5));
    }

    #[test]
    fn test_parse_result_structure() {
        let result = ParseResult {
            files: vec![],
            warnings: vec!["test warning".to_string()],
            errors: vec![],
        };

        assert!(result.files.is_empty());
        assert_eq!(result.warnings.len(), 1);
        assert!(result.errors.is_empty());
    }

    #[test]
    fn test_basic_parsing_success() {
        let input = "--------------------\nfile: test.rs\n--------------------\n    fn main() {}\n--------------------";
        let result = Parser::parse(input).unwrap();

        assert_eq!(result.files.len(), 1);
        assert_eq!(result.files[0].path, "test.rs");
        assert_eq!(result.files[0].content, vec!["fn main() {}"]);
    }

    #[test]
    fn test_invalid_separator_error() {
        let input = "-------------------\nfile: test.rs\n"; // 19 dashes instead of 20
        let result = Parser::parse(input);

        assert!(result.is_err());
        if let Err(ImportError::Format { line, message }) = result {
            assert_eq!(line, 1);
            assert!(message.contains("expected separator with exactly 20 dashes"));
        }
    }

    #[test]
    fn test_invalid_file_path_error() {
        let input = "--------------------\ntest.rs\n"; // Missing "file: " prefix
        let result = Parser::parse(input);

        assert!(result.is_err());
        if let Err(ImportError::Format { line, message }) = result {
            assert_eq!(line, 2);
            assert!(message.contains("expected 'file: <path>'"));
        }
    }

    #[test]
    fn test_empty_file_path_error() {
        let input = "--------------------\nfile: \n"; // Empty path
        let result = Parser::parse(input);

        assert!(result.is_err());
        if let Err(ImportError::PathValidation { path, reason }) = result {
            assert!(path.is_empty());
            assert!(reason.contains("cannot be empty"));
        }
    }

    // Test parsing multiple files in a single input
    #[test]
    fn test_multiple_files_parsing() {
        let input = r#"--------------------
file: first.rs
--------------------
    pub fn hello() {}
--------------------
file: second.py
--------------------
    def world():
        pass
--------------------"#;

        let result = Parser::parse(input).unwrap();

        assert_eq!(result.files.len(), 2);

        // First file
        assert_eq!(result.files[0].path, "first.rs");
        assert_eq!(result.files[0].content, vec!["pub fn hello() {}"]);

        // Second file
        assert_eq!(result.files[1].path, "second.py");
        assert_eq!(result.files[1].content, vec!["def world():", "    pass"]);
    }

    // Test handling end-of-file without final separator
    #[test]
    fn test_eof_handling_without_final_separator() {
        let input = "--------------------\nfile: test.rs\n--------------------\n    fn main() {}";
        let result = Parser::parse(input).unwrap();

        assert_eq!(result.files.len(), 1);
        assert_eq!(result.files[0].path, "test.rs");
        assert_eq!(result.files[0].content, vec!["fn main() {}"]);
    }

    // Test parsing files with empty content
    #[test]
    fn test_empty_file_content() {
        let input =
            "--------------------\nfile: empty.txt\n--------------------\n--------------------";
        let result = Parser::parse(input).unwrap();

        assert_eq!(result.files.len(), 1);
        assert_eq!(result.files[0].path, "empty.txt");
        assert!(result.files[0].content.is_empty());
    }

    // Test content indentation handling (4-space removal)
    #[test]
    fn test_content_indentation_removal() {
        let input = r#"--------------------
file: indented.txt
--------------------
    line with 4 spaces
        line with 8 spaces (4 removed)
	not tab indented
--------------------"#;

        let result = Parser::parse(input);

        // This should fail because the tab line doesn't have 4 spaces
        assert!(result.is_err());
        if let Err(ImportError::Format { line, message }) = result {
            assert_eq!(line, 6); // Line with tab (counting from 1 in the raw string)
            assert!(message.contains("content line must be indented with exactly 4 spaces"));
        }
    }

    // Test proper indentation handling and preservation
    #[test]
    fn test_proper_indentation_removal() {
        let input = r#"--------------------
file: code.rs
--------------------
    fn main() {
        println!("Hello");
    }
--------------------"#;

        let result = Parser::parse(input).unwrap();

        assert_eq!(result.files.len(), 1);
        assert_eq!(
            result.files[0].content,
            vec!["fn main() {", "    println!(\"Hello\");", "}"]
        );
    }

    // Test validation of separator format (exactly 20 dashes)
    #[test]
    fn test_wrong_separator_content() {
        let input = "--------------------\nfile: test.rs\n-------------------\n    content\n"; // 19 dashes in content separator
        let result = Parser::parse(input);

        assert!(result.is_err());
        if let Err(ImportError::Format { line, message }) = result {
            assert_eq!(line, 3);
            assert!(message.contains("expected content separator with exactly 20 dashes"));
        }
    }

    // Test parser state machine transition validation
    #[test]
    fn test_state_transitions() {
        let mut parser = Parser::new();

        // Initial state
        assert_eq!(parser.state, ParserState::ExpectingSeparator);

        // Process separator
        parser.process_line("--------------------").unwrap();
        assert_eq!(parser.state, ParserState::ExpectingFilePath);

        // Process file path
        parser.process_line("file: test.rs").unwrap();
        assert_eq!(parser.state, ParserState::ExpectingContentSeparator);

        // Process content separator
        parser.process_line("--------------------").unwrap();
        assert_eq!(parser.state, ParserState::ReadingContent);

        // Process content line
        parser.process_line("    some content").unwrap();
        assert_eq!(parser.state, ParserState::ReadingContent);

        // Process end separator (should transition to ExpectingFilePath)
        parser.process_line("--------------------").unwrap();
        assert_eq!(parser.state, ParserState::ExpectingFilePath);
    }

    // Test accurate line number tracking for error reporting
    #[test]
    fn test_line_number_tracking() {
        let input = "--------------------\nfile: test.rs\n--------------------\n    line1\n    line2\n--------------------";
        let result = Parser::parse(input).unwrap();

        assert_eq!(result.files.len(), 1);
        assert_eq!(result.files[0].line_range, (2, 5)); // file path at line 2, last content at line 5
    }
}
